// AUTO-GENERATED from shared/metrics.ts — DO NOT EDIT THIS FILE.
// Edit shared/metrics.ts instead, then run `npm run sync-shared` in web/.
// The metrics-sync test fails CI if this copy drifts from the source.
export const VELOCITY_DAYS = 14;
export const VELOCITY_LIQUID = 15;
export const PPD_N = 6;
export const JUNK_RATE_FALLBACK = 0.10;

export interface OrderForPpd {
  price: number;
  quantity: number;
}

export function computePpdAtN(
  orders: OrderForPpd[],
  ducats: number,
  n: number,
): { ppdAtN: number | null; shallow: boolean } {
  if (orders.length === 0) return { ppdAtN: null, shallow: false };

  let cumQty = 0;
  let cumCost = 0;
  for (const o of orders) {
    const take = Math.min(o.quantity, n - cumQty);
    cumCost += o.price * take;
    cumQty += take;
    if (cumQty >= n) break;
  }

  if (cumQty >= n) {
    return { ppdAtN: (ducats * n) / cumCost, shallow: false };
  }

  return {
    ppdAtN: cumQty > 0 ? (ducats * cumQty) / cumCost : null,
    shallow: true,
  };
}

export function computeVelocity(volumes: number[], windowDays: number): number {
  return volumes.reduce((a, b) => a + b, 0) / windowDays;
}

export function computeJunkRateFromRanked(
  items: { ppd_at_n: number | null; shallow: boolean }[],
  fallback: number = JUNK_RATE_FALLBACK,
): number {
  const withDepth = items.filter((i) => i.ppd_at_n !== null && !i.shallow);
  const top = withDepth.slice(0, 20);
  if (top.length === 0) return fallback;
  const values = top.map((i) => i.ppd_at_n!).sort((a, b) => a - b);
  const mid = Math.floor(values.length / 2);
  const median =
    values.length % 2 === 0
      ? (values[mid - 1] + values[mid]) / 2
      : values[mid];
  return 1 / median;
}

export function computeBaroRoi(
  resaleMedian: number,
  ducatCost: number,
  junkRate: number,
): number {
  return resaleMedian - ducatCost * junkRate;
}

export function isSpecialVisit(
  relay: string | null,
  itemCount: number,
): boolean {
  return (relay != null && /tennocon/i.test(relay)) || itemCount >= 150;
}

// ── Recovery Curve & Advisor (M12) ──────────────────────────────────

export const RECOVERY_THRESHOLD = 0.95;
export const MAX_RECOVERY_DAYS = 42;
export const BASELINE_WINDOW_DAYS = 30;
export const BARO_CYCLE_DAYS = 14;

export interface DailyPrice {
  date: string;
  median: number;
}

export interface NormalizedPoint {
  day: number;
  value: number;
}

export interface RecoveryCurvePoint {
  day: number;
  median: number;
}

export type Verdict = "BUY & HOLD" | "BUY & FLIP" | "SKIP";

export interface BasketCandidate {
  index: number;
  ducatCost: number;
  profitPerDucat: number;
}

export function computeMedian(values: number[]): number | null {
  if (values.length === 0) return null;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0
    ? (sorted[mid - 1] + sorted[mid]) / 2
    : sorted[mid];
}

export function computeBaseline(
  prices: DailyPrice[],
  beforeDate: string,
  windowDays: number = BASELINE_WINDOW_DAYS,
): number | null {
  const before = new Date(beforeDate).getTime();
  const windowStart = before - windowDays * 86_400_000;
  const windowPrices = prices
    .filter((p) => {
      const t = new Date(p.date).getTime();
      return t >= windowStart && t < before;
    })
    .map((p) => p.median);
  return computeMedian(windowPrices);
}

export function buildRecoverySeries(
  prices: DailyPrice[],
  departureDate: string,
  baseline: number,
  maxDays: number = MAX_RECOVERY_DAYS,
): NormalizedPoint[] {
  if (baseline <= 0) return [];
  const depDate = departureDate.slice(0, 10);
  const depTime = new Date(depDate + "T00:00:00Z").getTime();
  const result: NormalizedPoint[] = [];
  for (const p of prices) {
    const pTime = new Date(p.date + "T00:00:00Z").getTime();
    const day = Math.round((pTime - depTime) / 86_400_000);
    if (day >= 0 && day <= maxDays) {
      result.push({ day, value: p.median / baseline });
    }
  }
  result.sort((a, b) => a.day - b.day);
  return result;
}

export function poolMedianCurve(
  allSeries: NormalizedPoint[][],
  maxDays: number = MAX_RECOVERY_DAYS,
): RecoveryCurvePoint[] {
  if (allSeries.length === 0) return [];
  const byDay = new Map<number, number[]>();
  for (const series of allSeries) {
    for (const point of series) {
      if (!byDay.has(point.day)) byDay.set(point.day, []);
      byDay.get(point.day)!.push(point.value);
    }
  }
  const curve: RecoveryCurvePoint[] = [];
  for (let day = 0; day <= maxDays; day++) {
    const values = byDay.get(day);
    if (!values?.length) continue;
    const med = computeMedian(values);
    if (med !== null) curve.push({ day, median: med });
  }
  return curve;
}

export function extractRecoveryDays(
  curve: RecoveryCurvePoint[],
  threshold: number = RECOVERY_THRESHOLD,
): number | null {
  for (const point of curve) {
    if (point.median >= threshold) return point.day;
  }
  return null;
}

export function computeRestockInterval(
  visitIndices: number[],
): number | null {
  if (visitIndices.length < 2) return null;
  const sorted = [...visitIndices].sort((a, b) => a - b);
  const gaps: number[] = [];
  for (let i = 1; i < sorted.length; i++) {
    gaps.push(sorted[i] - sorted[i - 1]);
  }
  return computeMedian(gaps);
}

export function computeBaselineDrift(
  prices: DailyPrice[],
  referenceDate: string,
  shortWindowDays: number = 90,
  longWindowDays: number = 365,
): { drift: number; shortBaseline: number; longBaseline: number } | null {
  const shortBaseline = computeBaseline(prices, referenceDate, shortWindowDays);
  const longBaseline = computeBaseline(prices, referenceDate, longWindowDays);
  if (shortBaseline === null || longBaseline === null || longBaseline === 0)
    return null;
  return {
    drift: (shortBaseline - longBaseline) / longBaseline,
    shortBaseline,
    longBaseline,
  };
}

export function isInTennoConWindow(
  specialVisitDates: string[],
  currentDate: string,
  windowWeeks: number = 6,
): boolean {
  const current = new Date(currentDate).getTime();
  const windowMs = windowWeeks * 7 * 86_400_000;
  for (const dateStr of specialVisitDates) {
    const visitTime = new Date(dateStr).getTime();
    const diff = visitTime - current;
    if (diff >= 0 && diff <= windowMs) return true;
  }
  return false;
}

export function computeAdvisorVerdict(
  sellNowProfit: number,
  holdProfit: number | null,
  holdDays: number | null,
  ducatCost: number,
): {
  verdict: Verdict;
  profitPerDay: number | null;
  profitPerDucat: number;
} {
  if (holdProfit === null || holdDays === null || holdDays <= 0) {
    if (sellNowProfit > 0) {
      return {
        verdict: "BUY & FLIP",
        profitPerDay: null,
        profitPerDucat: ducatCost > 0 ? sellNowProfit / ducatCost : 0,
      };
    }
    return { verdict: "SKIP", profitPerDay: null, profitPerDucat: 0 };
  }
  const bestProfit = Math.max(sellNowProfit, holdProfit);
  if (bestProfit <= 0) {
    return { verdict: "SKIP", profitPerDay: null, profitPerDucat: 0 };
  }
  const profitPerDucat = ducatCost > 0 ? bestProfit / ducatCost : 0;
  if (holdProfit > sellNowProfit) {
    return {
      verdict: "BUY & HOLD",
      profitPerDay: (holdProfit - sellNowProfit) / holdDays,
      profitPerDucat,
    };
  }
  return { verdict: "BUY & FLIP", profitPerDay: null, profitPerDucat };
}

// ── Sell Signals (M13) ─────────────────────────────────────────────

export type SellSignalCondition = "target_hit" | "recovery_elapsed" | "restocked";

export interface SellSignalInput {
  currentMedian: number;
  targetPrice: number;
  acquiredAt: string;
  recoveryDays: number | null;
  isRestocked: boolean;
  // Every condition that has ever fired for this position. Tracking only the
  // most recent condition lets alternating conditions re-alert forever.
  alertedConditions: string[];
  now: string;
}

export function evaluateSellSignal(input: SellSignalInput): SellSignalCondition | null {
  const {
    currentMedian, targetPrice, acquiredAt, recoveryDays,
    isRestocked, alertedConditions, now,
  } = input;

  if (isRestocked && !alertedConditions.includes("restocked")) return "restocked";

  if (currentMedian >= targetPrice && !alertedConditions.includes("target_hit")) return "target_hit";

  if (recoveryDays !== null) {
    const daysHeld = Math.floor(
      (new Date(now).getTime() - new Date(acquiredAt).getTime()) / 86_400_000,
    );
    if (daysHeld >= recoveryDays && !alertedConditions.includes("recovery_elapsed")) return "recovery_elapsed";
  }

  return null;
}

export interface SellSignalPosition {
  id: number;
  itemName: string;
  qty: number;
  costPlat: number;
  currentMedian: number;
  targetPrice: number;
  signal: SellSignalCondition;
  pnl: number;
}

export function formatSellSignalMessage(
  positions: SellSignalPosition[],
  masteryRank: number,
  siteUrl?: string,
): string {
  if (positions.length === 0) return "";

  positions.sort((a, b) => b.pnl - a.pnl);

  const lines: string[] = [];

  if (positions.length > 3) {
    lines.push(`**${positions.length} positions signaling** (sorted by P/L):`);
    lines.push("");
    for (const p of positions) {
      const sign = p.pnl >= 0 ? "+" : "";
      lines.push(
        `- **${p.itemName}** x${p.qty}: ${signalLabel(p.signal)} — ` +
        `current ${Math.round(p.currentMedian)}p, target ${Math.round(p.targetPrice)}p, ` +
        `est. P/L ${sign}${Math.round(p.pnl)}p`,
      );
    }
    lines.push("");
    lines.push(`Daily trade cap: ${masteryRank} trades (MR${masteryRank}). Prioritize by P/L.`);
  } else {
    for (const p of positions) {
      const sign = p.pnl >= 0 ? "+" : "";
      lines.push(
        `**${p.itemName}** x${p.qty}: ${signalLabel(p.signal)}\n` +
        `Current median: ${Math.round(p.currentMedian)}p | Target: ${Math.round(p.targetPrice)}p | ` +
        `Est. P/L: ${sign}${Math.round(p.pnl)}p`,
      );
    }
  }

  if (siteUrl) {
    lines.push("");
    lines.push(`${siteUrl.replace(/\/$/, "")}/positions`);
  }

  return lines.join("\n");
}

function signalLabel(condition: SellSignalCondition): string {
  switch (condition) {
    case "target_hit": return "Target price reached";
    case "recovery_elapsed": return "Recovery window elapsed";
    case "restocked": return "Restocked by Baro — price will drop, sell now";
  }
}

// ── Visit-level verdict ─────────────────────────────────────────────
// Answers "is this visit worth spending ducats on?" before the user reads
// per-mod rows. Transparent thresholds, no weighting magic: a visit is as
// good as the number of profitable buys and the plat they add up to.

export interface VisitVerdict {
  tier: "STRONG" | "SELECTIVE" | "SKIP";
  buyCount: number;
  totalProfit: number; // best-leg (flip vs hold) profit summed over BUY mods
}

export function computeVisitVerdict(
  mods: { verdict: Verdict; sellNowProfit: number; holdProfit: number | null }[],
): VisitVerdict {
  const buys = mods.filter(
    (m) => m.verdict === "BUY & FLIP" || m.verdict === "BUY & HOLD",
  );
  const totalProfit = buys.reduce(
    (s, m) => s + Math.max(m.sellNowProfit, m.holdProfit ?? m.sellNowProfit),
    0,
  );
  const tier: VisitVerdict["tier"] =
    buys.length === 0
      ? "SKIP"
      : buys.length >= 5 && totalProfit >= 100
        ? "STRONG"
        : "SELECTIVE";
  return { tier, buyCount: buys.length, totalProfit };
}

export function greedyBasketOptimize(
  items: BasketCandidate[],
  ducatWallet: number,
): number[] {
  const sorted = items
    .filter((i) => i.profitPerDucat > 0)
    .sort((a, b) => b.profitPerDucat - a.profitPerDucat);
  const selected: number[] = [];
  let remaining = ducatWallet;
  for (const item of sorted) {
    if (item.ducatCost <= remaining) {
      selected.push(item.index);
      remaining -= item.ducatCost;
    }
  }
  return selected;
}

// ── Next-Visit Forecast ────────────────────────────────────────────
// Between visits: which items are statistically "due" to reappear, from each
// item's own restock cadence. gapAtNext = visits between the item's last
// appearance and the UPCOMING visit; dueRatio = gapAtNext / median gap.
// >=1 means the usual wait is over.

export type ForecastLikelihood = "OVERDUE" | "DUE" | "POSSIBLE" | "UNLIKELY";

export interface ForecastItemInput {
  item_name: string;
  ducat_cost: number | null;
  credit_cost: number | null;
  // Appearance indexes over normal visits, 0 = most recent visit.
  visits_ago: number[];
}

export interface ForecastEntry {
  item_name: string;
  ducat_cost: number | null;
  credit_cost: number | null;
  appearances: number;
  lastSeenVisitsAgo: number;
  medianGap: number;
  dueRatio: number;
  likelihood: ForecastLikelihood;
}

export function likelihoodFor(dueRatio: number): ForecastLikelihood {
  if (dueRatio >= 1.5) return "OVERDUE";
  if (dueRatio >= 0.9) return "DUE";
  if (dueRatio >= 0.6) return "POSSIBLE";
  return "UNLIKELY";
}

export function computeVisitForecast(
  items: ForecastItemInput[],
  minAppearances: number = 3,
): ForecastEntry[] {
  const out: ForecastEntry[] = [];
  for (const item of items) {
    if (item.visits_ago.length < minAppearances) continue;
    const medianGap = computeRestockInterval(item.visits_ago);
    if (medianGap === null || medianGap <= 0) continue;
    const lastSeenVisitsAgo = Math.min(...item.visits_ago);
    const gapAtNext = lastSeenVisitsAgo + 1;
    const dueRatio = gapAtNext / medianGap;
    out.push({
      item_name: item.item_name,
      ducat_cost: item.ducat_cost,
      credit_cost: item.credit_cost,
      appearances: item.visits_ago.length,
      lastSeenVisitsAgo,
      medianGap,
      dueRatio,
      likelihood: likelihoodFor(dueRatio),
    });
  }
  out.sort(
    (a, b) => b.dueRatio - a.dueRatio || a.item_name.localeCompare(b.item_name),
  );
  return out;
}
